# Generated by Django 3.2.3 on 2021-07-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='size',
        ),
    ]
